### PR TITLE
sign transaction

### PR DESCRIPTION
**Pull request by ramirez915**
created the sign transaction function and it's test function

### CODE REVIEW

**Comment by ramirez915** [comment]
don't know exactly why there are changes on the first 3 files...

**Comment by kstola2** [comment]
Did you git add all the files? You need to add them by name individually

**Comment by ramirez915** [comment]
I did not since I did it straight from the GitHub gui this time

**Comment by kstola2** [comment]
Oh well if you do it in the Github GUI you need to check only the boxes next to the files you want to add. It automatically assumes you want to add all of them.

**Comment by ramirez915** [comment]
Alright cool! So what would be the best way to go about retrying? Deleting this branch to make a new one and then do it again checking only the two files? Or is there another way to undo the current pull request and redo it with only the two file?

**Comment by kstola2** [comment]
I would delete the branch and the pr then make a new branch to add the files to.

**Comment by ramirez915** [comment]
Sweet sounds good thanks Karol!

**Pull request closed without merging**
