### PR TITLE
Updated master_test.py and run_all_tests.sh

### PR DESCRIPTION
**Pull request by jldistefano**
I believe your problem was similar to the ones with the individual test files, that they were being called from outside their parent directory. I updated the files to take this into account. Also for the .py file, I didn't think hardcoding the name of each file wasn't a very efficient solution, so I created a for loop that runs all .py files in that directory that are not master_test.py.

### CODE REVIEW

**Comment by kstola2** [comment]
What sort of output are you getting when you run these files?

**Comment by kstola2** [comment]
I'm getting the following error when I run the `master_test.py` file:

`'python3' is not recognized as an internal or external command, operable program or batch file.`

Which doesn't make sense to me but it might be because I'm running it in vscode.

**Comment by kstola2** [comment]
Also when I run the shell file in terminal, it does execute but it appears to only run a few of the tests and most of them fail, which is also strange.

**Comment by jldistefano** [comment]
Some of the tests fail on my machine as well, however they also failed when I ran them individually. The py file works as intended however I have just tested the script and found that it does not work when run outside of its parent directory

**Comment by kstola2** [comment]
Does the script work when you run it within its directory?

**Comment by jldistefano** [comment]
Yes, or at least it has the same effect as the .py file. The tests that are failing for me have always failed before the restructuring anyways.

**Comment by kstola2** [comment]
This might have something to do with the way pathing works on Linux vs. Windows.

**Comment by kstola2** [comment]
One fallback solution (although ugly) would be to create a function in each test file that calls `unittest.main()`, then in the master test file, import all those functions and call all of them...

**Comment by jldistefano** [comment]
The py file works fine for me, the only thing that is not working is calling the script from outside of its parent directory, which I'm not sure would ever really be necessary. I've tried having a command such as `os.system('network.test.py')`, but it tells me that permission is denied. Instead running it with python3 works fine on my machine. Do you enter a console command to run these py files in vscode, and if so what is it?

**Comment by kstola2** [comment]
Nah in VSCode you can just right click on the file and click run in terminal, which is the equivalent of doing `python some_file.py`

**Comment by kstola2** [comment]
I pushed a change, run `master_test.py` and see if it works for you. I'm not sure what to do about the script, but I don't really plan on using it instead of `master_test.py` anyway. But if it works for you and you're going to use it then that's okay.

**Comment by jldistefano** [comment]
Works good for me, did you also want to update run_all_tests.sh or is the master_test.py sufficient? Also I imagine it would work the same on a mac as on a linux machine, but we should test it.

**Comment by jldistefano** [comment]
Actually I looked into it and updated the branch with a version of run_all_tests.sh that does a platform check. If it doesn't work, put the line `echo "$OSTYPE"` at the beginning of the script and let me know what it spits out into console.

**Comment by kstola2** [comment]
Im gonna have zach try this cause he has a mac. I think the python file is sufficient to achieve what we want. Any script is just extra goodness.

**Comment by bashbashbash** [comment]
Run in macOS. Pulled and ran latest master_test.py on branch 'jdist_branch'. Errors appeared in 'test_01_constructor' and 'test_slice_nonce'. Fail in 'test_mine'. See attached screenshots for details. Let me know if you want me to run further tests.

screen shot 2018-12-15 at 1 26 36 pm
screen shot 2018-12-15 at 1 27 20 pm

**Comment by kstola2** [comment]
@jdistefano do you get these errors when you ran yours?

**Comment by jldistefano** [comment]
I don't get the `test_constructor_01()` one, but I've been getting the nonce and parse output ones since the start.

**Comment by kstola2** [comment]
We need to fix this. Perhaps for those tests that fail on linux we can put a if else clause?

**Comment by jldistefano** [comment]
[It has to do with the size of long integers across systems](https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os)

**Comment by kstola2** [comment]
I will test to see if a python unsigned long has the same range as python unsigned integer, which means we can change all the long variables to ints.

**Comment by jldistefano** [comment]
The page I linked suggests using a 'long long' which is always 8 bytes across all platforms

**Comment by kstola2** [comment]
That actually may be a better alternative. If you changed those tests to involve long longs do they pass?

**Comment by jldistefano** [comment]
I don't think its the tests that are necessarily wrong, well they are but its the source functions at issue. We need to change the `long_to_bytes()` function to pack it as a long long rather than a long to ensure it is consistent across platforms

**Comment by kstola2** [comment]
That's what I'm saying you could try out. Replace the 'L' with a 'Q' in the conversion functions

**Comment by jldistefano** [comment]
Yeah, I changed all the L's in pack/unpack statements to Q's. And everything regarding long integers to 8 bytes. No errors now

**Comment by kstola2** [comment]
Okay. Can you create an issue thats objective is to change anything involving those functions so that all tests pass?

**Comment by kstola2** [comment]
I can however we will need to revisit it for mac users.

**Comment by jldistefano** [comment]
Ok, I'll just make a new branch.

**Pull request merged**
