### PR TITLE
Added forge_block method

### PR DESCRIPTION
**Pull request by JoshuaRM**
Added forge_block method. This method receives a list of `transactions` as a parameter.
I made minor import changes in `transactions.py`, due to circular dependencies.
Solves #190

### CODE REVIEW

**Comment by kstola2** [comment]
Can you make your own branch on the repo and then make a PR from there?

**Comment by JoshuaRM** [comment]
Yes, I will create a branch.
In regards to the changes in `transactions.py`, I needed to make these in order to avoid circular dependencies because block needs to use the `_get_merkle_root` function from `transactions.py`

**Comment by kstola2** [comment]
Okay I see what you're saying.

**Comment by kstola2** [comment]
It might make more sense to move the merkle function into block anyway

**Comment by JoshuaRM** [comment]
I will work on moving the merkle root functions into the `block.py`

**Comment by kstola2** [comment]
Okay just note there was a major project restructuring last night so a lot of stuff moved around.

**Comment by kstola2** [comment]
What's the status on this PR?

**Comment by kstola2** [comment]
I'm gonna close this PR for now until the branch gets up to date.

**Pull request closed without merging**
