### PR TITLE
set up gui.py

### PR DESCRIPTION
**Pull request by Vineet77**
I created the new ui files, called gui.py. The title of the window has been setup.

### CODE REVIEW

**Comment by Vineet77** [comment]
Ok, I'll remove the button, but is it ok if I set up the GridLayout (along with the CentralWidget)?

**Comment by jldistefano** [comment]
I don't really believe that the window needs to scale, but you can add a gridlayout if you want to

**Comment by jldistefano** [comment]
We'll likely end up messing with the size and scalability later, but for now its good.

**Comment by kstola2** [comment]
Uhhh why was this merged into master?

**Comment by jldistefano** [comment]
Wow, I can't believe I didn't notice that it a pull request on master. Do I have the permissions to revert master?

**Comment by kstola2** [comment]
Try it out and let me know if you can't.

**Pull request merged**
