### PR TITLE
Restructured Project and Updated Test Files Accordingly

### PR DESCRIPTION
**Pull request by jldistefano**
Unfortunately I do not know how to write a setup.py file, and I have no idea what the requirements for this project are, so those are currently unwritten.

### CODE REVIEW

**Comment by jldistefano** [comment]
Sure, also which tests are failing?

**Comment by kstola2** [comment]
All of them, they're getting import errors.

**Comment by jldistefano** [comment]
That's strange, my tests are passing. Is the error something like... 
`from block import *`
`ModuleNotFoundError: No module named 'block'`

**Comment by kstola2** [comment]
Yep

**Comment by jldistefano** [comment]
Ok, I figured it out. The way I run it is by creating a terminal in the same directory as the test files, so when the `sys.path.append()` statement runs, it will move the current directory to the correct directory. But when I tested it on vscode on windows, the terminal is not in the correct directory, but when I moved it there it works fine. So I had to add the statement `sys.path.append(sys.path[0] + "/../src/data_structures")` to ensure it would look in the correct place for the files.

**Pull request closed without merging**
