### PR TITLE
Changed Length of Labels in ui.py

### PR DESCRIPTION
**Pull request by jldistefano**
I put the title in its own frame so it could stretch with the columns. I set the columns to have 'weights' in line 64, and weighted the labels less so than the title. If you wanted to keep the window at a fixed size the entire time, we could avoid the QGridLayout() entirely and just manually set the positions and lengths of things. Otherwise we could also have the title span multiple columns.

### CODE REVIEW

**Comment by kstola2** [comment]
I noticed that it works for the IP Address but not for the fields below it? Is it possible to anchor them so they don't grow vertically?

image

**Comment by jldistefano** [comment]
It's not really possible to lock a window to only grow horizontally and not vertically. Though it can sort of be done by adding a row below the rest that can stretch while the others do not stretch. That is now implemented in my branch.

**Comment by jldistefano** [comment]
I actually have been looking into it further and that is possible, it just increases the vertical space inbetween the labels as the window gets larger.

**Comment by kstola2** [comment]
Perhaps it would be a better idea to have those three labels in some kind of container that never is fixed in size? I'm just thinking of other solutions if possible.

**Comment by jldistefano** [comment]
That is certainly possible, there is an object in pyqt5 called QGroupBox that does just that.

**Comment by kstola2** [comment]
What's your judgment? Do you think that's a better option?

**Comment by jldistefano** [comment]
Yes, I would say it is better to keep the spacing between the labels consistent, especially since they do not change size. Also will the transaction history and console grow? or are they scroll boxes?

**Comment by kstola2** [comment]
I haven't really thought about those yet. The UI is a totally flexible part of the project because all the functionality lies underneath it. So whatever looks user-friendly and neat works.

**Comment by jldistefano** [comment]
It turns out that the group box will be slightly misaligned from the top of the window, so I left them seperated. But I did lock their heights. Also I have been also working on the other ui issues, so those will also show on my branch.

**Comment by kstola2** [comment]
Last idea: what if we shifted those three labels down one row, so IP will be where status is right now. Wouldn't that make them all the same height? It just seems a bit weird to have the IP box as large as the title box and the others be skinnier.

**Comment by kstola2** [comment]
I sent a message on slack

**Pull request closed without merging**
