### PR TITLE
added mine button

### PR DESCRIPTION
**Pull request by Vineet77**

### CODE REVIEW

**Comment by kstola2** [comment]
If you got files changed there were some things deleted that shouldn't have been deleted. You may have pulled from master instead of dev

**Comment by Vineet77** [comment]
For me, it say only ui.py was changed

**Comment by kstola2** [comment]
Yep that's correct

**Comment by Vineet77** [comment]
image

**Comment by Vineet77** [comment]
So wait, what is the problem lol?

**Comment by kstola2** [comment]
i'm talking about what was changed in ui.py.

**Comment by kstola2** [comment]
image

**Comment by kstola2** [comment]
That's just some of it.

**Comment by Vineet77** [comment]
Ok, I think I understand somewhat. I think my ui.py is behind, so some of the labels are different. All the changes for girdLayout.add().... that's because I had to add another column to the left, hence everything else had to be moved to the right by 1. I'll try to changes from the dev branch first.

**Comment by Vineet77** [comment]
Ok, all changes are now relevant to the mine button.

**Pull request merged**
