### PR TITLE
Re-added gui.py, and added background

### PR DESCRIPTION
**Pull request by jldistefano**

### CODE REVIEW

**Comment by kstola2** [comment]
Is the image supposed to display in the background?

**Comment by jldistefano** [comment]
Yes, is it not doing it on your machine?

**Comment by kstola2** [comment]
It is not. Is there something I need to install?

**Comment by jldistefano** [comment]
Did you also bring along the `qbertdark.png` file that was also in that branch?

**Comment by kstola2** [comment]
Yep it's in the directory.

**Comment by jldistefano** [comment]
It's working for me, are you just getting a black background?

**Comment by kstola2** [comment]
Yeah it's just black.

**Comment by jldistefano** [comment]
Are you getting any errors in the console?

**Comment by kstola2** [comment]
https://stackoverflow.com/questions/13438653/qimage-does-not-load-image-even-when-it-exists

When I run it in the console I get ModuleNotFound. Perhaps I need to pip install PyQt5?

**Comment by jldistefano** [comment]
Yes, I just tried it on a windows machine and got the same error. You do need to `pip install pyqt5`

**Comment by kstola2** [comment]
Are you sure it's called pyqt5? Cause I'm running pip install and it can't find it.

**Comment by jldistefano** [comment]
It is called pyqt5 yeah, you could try updating pip itself using `python -m pip install --upgrade pip`

**Comment by kstola2** [comment]
I did that now I'm getting an ImportError lol let me look into this

**Comment by jldistefano** [comment]
I just installed it on my windows machine, windows 7 if that helps at all.

**Comment by jldistefano** [comment]
I made a change that might fix it on your machine, it has to do with how vscode runs py files from outside their parent directory

**Comment by jldistefano** [comment]
The way it was, it only checked for the file in the current directory. I changed it to use an absolute file path instead.

**Pull request merged**
